/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import javafx.application.Application;
import javafx.application.Platform;
import javafx.geometry.Dimension2D;
import javafx.scene.Scene;
import javafx.scene.canvas.Canvas;
import javafx.scene.control.Label;
import javafx.scene.layout.Pane;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;
import javafx.stage.WindowEvent;


public class App extends Application{
    private Game game;
    private Canvas primer_plano;
    private Canvas fondo;
    private Scene scene;
    private int width = 384;
    private int height = 14*16;

    // private String pathfondos = "escenarios.png";
    @Override
    public void start(Stage stage) {
        //var javaVersion = SystemInfo.javaVersion();
        //var javafxVersion = SystemInfo.javafxVersion();

        primer_plano = new Canvas(this.width * Game.SCALE, (this.height) * Game.SCALE); //Label("Hello, JavaFX " + javafxVersion + ", running on Java " + javaVersion + ".");
        fondo = new Canvas(this.width * Game.SCALE, (this.height) * Game.SCALE); //Label("Hello, JavaFX " + javafxVersion + ", running on Java " + javaVersion + ".");

        Pane root = new Pane(fondo, primer_plano);

        scene = new Scene(root, this.width * Game.SCALE, (this.height) * Game.SCALE);
        this.game = new Game(primer_plano.getGraphicsContext2D(),
                fondo.getGraphicsContext2D(),
                new Dimension2D(width, height));
        this.registerKeys();
        stage.setResizable(false);
        stage.setOnCloseRequest((WindowEvent t) -> {
            Platform.exit();
            // game.stop();
            System.exit(0);
        });
        stage.setScene(scene);
        stage.show();
        this.game.start();
    }

    private void registerKeys() {
        scene.setOnKeyReleased(e -> {
            this.game.onKeyReleased(
                    e.getCode());
        });
        scene.setOnKeyPressed(e -> {
            this.game.onKeyPressed(e.getCode());

        });
    }

    public static void main(String[] args) {
        launch();
}
}
